import type { Option, SortOption } from "~/models/FilterOptions";
const CATEGORIES_PARSER: Option[] = [
  { title: { eng: "Decks", ua: "Дошки" }, value: "decks" },
  { title: { eng: "Trucks", ua: "Підвіски" }, value: "trucks" },
  { title: { eng: "Wheels", ua: "Колеса" }, value: "wheels" },
  { title: { eng: "Other", ua: "Інше" }, value: "other" },
  { title: { eng: "Completes", ua: "Компліти" }, value: "completes" },
  { title: { eng: "Leather", ua: "Шкіра" }, value: "leather" },
  { title: { eng: "Seude", ua: "Замша" }, value: "seude" },
  { title: { eng: "Canvas", ua: "Текстиль" }, value: "canvas" },
  { title: { eng: "Shoes", ua: "Взуття" }, value: "shoes" },
  { title: { eng: "Barely used", ua: "Мало вживаний" }, value: "barely" },
  { title: { eng: "New", ua: "Новий" }, value: "new" },
  { title: { eng: "Roughly used", ua: "Сильно вживаний" }, value: "roughly" },
  { title: { eng: "Skates", ua: "Скейти" }, value: "skateboards" },
];

const BRANDS_NAMES = [
  "Baker",
  "5Boro",
  "Alien Workshop",
  "Alltimers",
  "Almost",
  "Anti Hero",
  "April",
  "Bacon",
  "Birdhouse",
  "Blueprint",
  "Chocolate",
  "Creature",
  "Darkroom",
  "Darkstar",
  "Deathwish",
  "DGK",
  "Dogtown",
  "Element",
  "Enjoi",
  "Flip",
  "Foundation",
  "Frog",
  "Girl",
  "Globe",
  "Habitat",
  "Heroin",
  "HUF",
  "Killing Floor",
  "Krooked",
  "Lovesick",
  "Madness",
  "Magenta",
  "Meow",
  "Metal",
  "Mini Logo",
  "Monarch Project",
  "Piss Drunx",
  "Plan B",
  "Polar",
  "Powell",
  "Primitive",
  "Quasi",
  "Real",
  "Santa Cruz",
  "Shorty's",
  "Sk8 Mafia",
  "Skate Warehouse",
  "StrangeLove",
  "Suicidal Skates",
  "Thank You",
  "The Heart Supply",
  "The Heated Wheel",
  "Theories",
  "There",
  "Toy Machine",
  "Transportation Unit",
  "Uma Landsleds",
  "Unity",
  "Verb",
  "Welcome",
  "WKND",
  "Zero",
  "Ace",
  "Bullet",
  "Independent",
  "Krux",
  "Royal",
  "Slappy",
  "Tensor",
  "Thunder",
  "Venture",
  "Bones Wheels",
  "Blind",
  "OJ",
  "Portland Wheel Company",
  "Ricta",
  "Satori",
  "Slime Balls",
  "Snot",
  "Spitfire",
  "Bones Bearings",
  "Andale",
  "Black Panther",
  "Bronson Speed Co.",
  "Cortina Bearing Co.",
  "Modus",
  "Shake Junt",
  "SKF",
  "Speed Demons",
  "Adidas",
  "Converse Skateboarding",
  "DC",
  "Emerica",
  "eS",
  "Fallen",
  "Lakai",
  "Last Resort AB",
  "New Balance Numeric",
  "Nike SB",
  "Vans",
  "Volcom",
];
const BRANDS = BRANDS_NAMES.map((brand) => ({
  title: brand,
  value: brand.toLowerCase().replace(/\s+/g, "_"),
}));

const CONDITIONS: Option[] = [
  { title: { eng: "New", ua: "Новий" }, value: "new" },
  { title: { eng: "Barely used", ua: "Майже новий" }, value: "barely" },
  { title: { eng: "Roughly used", ua: "Зношений" }, value: "roughly" },
];
const PRICE_SORT_OPTIONS: SortOption[] = [
  {
    title: { eng: "Highest price", ua: "Найвища ціна" },
    prop: "price",
    direction: "desc",
  },
  {
    title: { eng: "Lowest price", ua: "Найнижча ціна" },
    prop: "price",
    direction: "asc",
  },
];
const DATE_SORT_OPTIONS: SortOption[] = [
  {
    title: { eng: "The newest", ua: "Найновіші" },
    prop: "createdAt",
    direction: "desc",
  },
  {
    title: { eng: "The oldest", ua: "Найстаріші" },
    prop: "createdAt",
    direction: "asc",
  },
];
export const SORT_OPTIONS = DATE_SORT_OPTIONS.concat(PRICE_SORT_OPTIONS);
const DISCOVER_CONDITIONS: Option[] = [
  { title: { eng: "Any", ua: "Будь-який" }, value: "any" },
  ...CONDITIONS,
];

export {
  CATEGORIES_PARSER,
  BRANDS,
  CONDITIONS,
  PRICE_SORT_OPTIONS,
  DATE_SORT_OPTIONS,
  DISCOVER_CONDITIONS,
};
